### ISSUE TITLE
Docker image for the server.

### ISSUE THREAD

**Issue by aadrian** [turtl/api#2]
Please add a docker (and compose) file for the server to allow the users to easier install it, but also to test and send reproducible issues.

Thank you.

**Comment by orthecreedence** [comment]
This is a great idea, and many others have asked for this as well. I've put it into our tracker: https://trello.com/c/bbTVdCFM

**Comment by ArthurGarnier** [comment]
FYI : https://github.com/ArthurGarnier/turtl-docker

Probably not the best dockerfile, but it works :)

**Comment by orthecreedence** [comment]
Aurthur, this is great! I'll check it out and add it to the project's server page documentation.

**Comment by orthecreedence** [comment]
Thank you for your work on this =]
