### ISSUE TITLE
(ql:quickload :turtl) fail !

### ISSUE THREAD

**Issue by ArthurGarnier** [turtl/api#3]
# Step to reproduce

Just look my dockerfile : https://github.com/ArthurGarnier/turtl-docker/blob/master/dockerfile

# What's happening ?

In the quicklisp interpreter loading turtl seems to fail : 

```
cd /opt/api && echo '(load "start")' | /opt/ccl/lx86cl64 -l /root/quicklisp/setup.lisp
Welcome to Clozure Common Lisp Version 1.11-r16635  (LinuxX8664)!

CCL is developed and maintained by Clozure Associates. For more information
about CCL visit http://ccl.clozure.com.  To enquire about Clozure's Common Lisp
consulting services e-mail info@clozure.com or visit http://www.clozure.com.


? > Error: System "turtl" not found
> While executing: (:INTERNAL QUICKLISP-CLIENT::RECURSE QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY), in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Try again
> Type :? for other options.

```
I try to load each command in start.lisp manually (in lisp interpreter) but the behavior is the same, the first command (ql:quickload :turtl) fail : 

```
? (ql:quickload "turtl")
> Error: System "turtl" not found
> While executing: (:INTERNAL QUICKLISP-CLIENT::RECURSE QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY), in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Try again
> Type :? for other options.
```

Did I miss something ? 

Thanks ! Your work seems great !

**Comment by orthecreedence** [comment]
Ah so I think you might need to add 

```
(pushnew "./" asdf:*central-registry* :test #'equal)
```

to your ~/.ccl-init.lisp file. This tells ASDF/quicklisp that it can search in the *current* directory for .asd files instead of the central registry. I think this is why it can't load Turtl. Try that and let me know if it works. Thanks for your time on making a Docker file!

**Comment by ArthurGarnier** [comment]
Hi, thank you for your answer !

pushnew works ! :D

But now I got another error : 

Loading "wookie"
; cc -m64 -I/root/quicklisp/dists/quicklisp/software/cffi_0.16.1/ -o /root/.cache/common-lisp/ccl-1.11-f96-linux-x64/root/quicklisp/dists/quicklisp/software/cl-libuv-20160208-git/grovel /root/.cache/common-lisp/ccl-1.11-f96-linux-x64/root/quicklisp/dists/quicklisp/software/cl-libuv-20160208-git/grovel.c
> Error: External process exited with code 71.
>        Command was: "cc" "-m64" "-I/root/quicklisp/dists/quicklisp/software/cffi_0.16.1/" "-o" "/root/.cache/common-lisp/ccl-1.11-f96-linux-x64/root/quicklisp/dists/quicklisp/software/cl-libuv-20160208-git/grovel" "/root/.cache/common-lisp/ccl-1.11-f96-linux-x64/root/quicklisp/dists/quicklisp/software/cl-libuv-20160208-git/grovel.c"
>        Output was:
>        
> While executing: CFFI-GROVEL:GROVEL-ERROR, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 > 

Did you already encounter this ? Seems to be related to "cc" but without error it's hard to debug...

**Comment by orthecreedence** [comment]
Hello! So it looks like it's trying to compile the cl-libuv wrapper for libuv and it either can't find libuv or doesn't have a C compiler installed (the error thrown by CFFI-GROVEL is not that helpful here). Is libuv installed in the container?

**Comment by ArthurGarnier** [comment]
Yes, libuv0.10-dev is installed. But gcc wasn't... my bad !

So, I installed it, but always get the same error. So I run into the container the "cc" command, and I got : 

/root/.cache/common-lisp/ccl-1.11-f96-linux-x64/root/quicklisp/dists/quicklisp/software/cl-libuv-20160208-git/grovel.c:7:22: fatal error: uv-errno.h: No such file or directory

I found lot of things about errno.h with google, but nothing about uv-errno.h... I tried `ln -s /usr/include/asm-generic /usr/include/asm ` but not helped...

**Comment by orthecreedence** [comment]
Hey Arthur, sorry for the lag, had a busy few weeks. I am kind of baffled by this. Can you do `:b` to get a stacktrace?

**Comment by ArthurGarnier** [comment]
In fact it was my fault, I made an infinite loop -_-"
Finally I complete the dockerfile, and it works fine !
