### ISSUE TITLE
turtl error:  "Authentication failed."

### ISSUE THREAD

**Issue by lumsgoy** [turtl/api#4]
I've set up a turtl server on my own personal server, and I'm quite excited by this great software ! Everything seems to work fine, I can start turtl on SBCL, which outpus:
```lisp
[package turtl-thread].
  <INFO> [20:56:22] turtl - Applying DB schema...
  <INFO> [20:56:22] turtl - Schema applied: (:TABLES-ADD NIL :INDEXES NIL
                                             :TABLES-ADD NIL :INDEXES NIL)
<NOTICE> [20:56:22] wookie - (start) Starting Wookie  0.0.0.0:8181
```

However, when I try to connect via my web browser through http://mydomain.com:8181, a webpage appears only displaying  "Authentication failed.". I also get the following errors in SBCL
```lisp
 <INFO> [21:09:28] wookie - "GET /" 401 24
 <ERROR> [21:09:28] wookie - (hook) Error running hooks: PRE-ROUTE: (socket #<TCP-SOCKET
                                                   {1007641103}>): Authentication failed.
  <INFO> [21:09:28] wookie - "GET NIL" 500 66
```

It's probably a quite straightforward mistake, but, any idea of what I'm missing ?
Thanks a lot !

**Comment by orthecreedence** [comment]
Hi, sorry for the late response, please try using Clozure CL instead of SBCL: http://ccl.clozure.com/download.html.

I've had much better luck with CCL running Turtl.

**Comment by oleerik** [comment]
Hello! I'm also experiencing this, both on SBCL and CCL.
Any more tips about what we can do to figure this out?

Please note that I'm an absolute beginner when it comes to everything lisp.

**Comment by oleerik** [comment]
Hmm. I can see that I get the same error when visiting https://api.turtl.it/apiv2 and user creation to that api doesn't work either. Very confused by this.

**Comment by orthecreedence** [comment]
Try this

```sh
cd ~/quicklisp/local-projects/
git clone https://github.com/orthecreedence/cl-hash-util.git
```

Restart Turtl and try again =]

**Comment by oleerik** [comment]
Thank you, sadly it doesn't seem like it made much of a difference, at least on CCL.
<NOTICE> [1467317369] wookie - (start) Starting Wookie  0.0.0.0:8181
  <INFO> [1467317377] wookie - "GET /" 401 24
 <ERROR> [1467317377] wookie - (hook) Error running hooks: PRE-ROUTE: (socket #<TCP-SOCKET #x302002A7591D>): Authentication failed.
  <INFO> [1467317377] wookie - "GET NIL" 500 66

**Comment by raphm** [comment]
I get the same error. I'm using SBCL 1.3.7, and I have cloned `cl-hash-util` per the instructions above.

`This is SBCL 1.3.7, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.`

`SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "turtl":
  Load 1 ASDF system:
    turtl
; Loading "turtl"
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
[package turtl-thread]`
`  <INFO> [1467643640] turtl - Applying DB schema...`
`  <INFO> [1467643640] turtl - Schema applied: (:TABLES-ADD NIL :INDEXES NIL)`
`<NOTICE> [1467643640] wookie - (start) Starting Wookie  0.0.0.0:8181`
`  <INFO> [1467643654] wookie - "GET /turtl" 401 24`
` <ERROR> [1467643654] wookie - (hook) Error running hooks: PRE-ROUTE: (socket #<TCP-SOCKET {10076E8EF3}>): Authentication failed.`

I'll see if I can't find some time to dig into this later today; hopefully there is a simple solution...

**Comment by kralewitz** [comment]
I'm getting the same message when trying to open the page directly in the browser, however when I launch either the Android or Linux client and point them to the URL of my server, they both work fine. Is there actually supposed to be anything on the root URL?

**Comment by shanff** [comment]
I've also used CL and SBCL and am getting Authentication failed.  Centos 7 with EPEL repos and minimal install with only required packages and git versions of LIsp, libuv and rethinkdb.  Also, hitting with https crashes program in both CL and SBCL (unrelated i'm sure).

**Comment by gladston3** [comment]
Hi,

I am experiencing the exact same error /:
Did anyone find a solution, yet?

Thx in advance
-gladston3

**Comment by raphm** [comment]
I think you are not supposed to connect to the port with a web browser. When I ran the server with CCL and pointed the desktop client to it, everything worked fine. I did not check with SBCL.

**Comment by shanff** [comment]
I just came here to agree with raphm after getting gladston3's update via email.  At the time I posted, I assumed that the webclient was built in.  Hit it by IP/port with a Turtl client and you should be good to go if the service is starting.

**Comment by psjbeisler** [comment]
This is an API after all, there is no "WEB UI".
https://github.com/turtl/api/issues/4#issuecomment-239637281
https://github.com/turtl/api/issues/4#issuecomment-239640644

**Comment by raphm** [comment]
Absolutely, and this is even implied in the documentation: "You can now point your clients at this port on your server, although it’s recommended to run it behind a proxy like Apache or Nginx." In hindsight this is obvious (as most things are).

Perhaps a stronger wording would be useful for new users: "You can now point a Turtl client application at this port on your server; however, it’s recommended to run the server behind a proxy like Apache or Nginx. There is no web user interface, so you must use a Turtl client application rather than simply pointing a web browser at the port."

**Comment by psjbeisler** [comment]
this can be closed right?
when more important issues should be open...
#6
