### ISSUE TITLE
Private server crashes if I try to use with android client 0.6.3

### ISSUE THREAD

**Issue by szimszon** [turtl/api#5]
Hi,

I installed a private server from github (git clone) into a docker container. The rethinkdb is running on the vm and not in a docker container.

The private server is working fine with the 64bit Ubuntu desktop app.

When I connect to the server with an android client after the auth. I got the following error in server:

<INFO> [21:04:16] wookie - "GET /users/572fa4.....a000001" 200 75
> Error: NIL found instead of hash table
> While executing: CL-HASH-UTIL:HGET, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading "launch.lisp"
> Type :? for other options.
1 > turtl.o...z.eu exited with code 0

And after that the server crashed.

**Comment by orthecreedence** [comment]
Is there any way to can get me a stacktrace? If you're in the REPL you can usually just type `:b`.

Otherwise, I can't see where the failure is happening. Also, are you using SBCL? If so, please give [Clozure CL](http://ccl.clozure.com/download.html) a try. I've had much better luck running Turtl on Clozure.

**Comment by szimszon** [comment]
(7FC0E5EB4450) : 0 (HGET #<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD> ("file")) 213
 (7FC0E5EB4480) : 1 (FUNCALL #'#<Anonymous Function #x3020028294BF> #<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD>) 61
 (7FC0E5EB44A0) : 2 (MATCHP2 #<Anonymous Function #x3020028294BF> #<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD> FUNCALL #<Compiled-function FUNCALL #x300000080BFF> NIL) 165
 (7FC0E5EB44E8) : 3 (SIMPLE-VECTOR-DELETE #<Anonymous Function #x3020028294BF> #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD>) FUNCALL #<Compiled-function FUNCALL #x300000080BFF> NIL 0 1 1 1152921504606846975) 749
 (7FC0E5EB4580) : 4 (DO-PROMISIFY #<COMPILED-LEXICAL-CLOSURE #x3020028FEBEF> :NAME "promisify: (REMOVE-IF-NOT (LAMBDA (NOTE) (AND (HGET NOTE '(\"file\")) (OR (HGET NOTE '(\"file\" \"id\")) (HGET NOTE '(\"file\" \"hash\"))))) NOTES)") 1157
 (7FC0E5EB4610) : 5 (FUNCALL #'#<Anonymous Function #x30200282961F> #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD>)) 261
 (7FC0E5EB4660) : 6 (FUNCALL #'#<(:INTERNAL BLACKBIRD-BASE:DO-ATTACH)> #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD>)) 1077
 (7FC0E5EB46F8) : 7 (RUN-PROMISE #<PROMISE name: "promisify: (REMOVE-IF (LAMBDA (NOTE) (LET ((BOARD-ID (GETHASH \"board_id\" NOTE))) (AND BOARD-ID (NOT (FIND BOARD-ID BOARD-IDS :TEST 'STRING=))))) NOTES)" finished: T errored: NIL forward: NIL #x3020028FF13D>) 661
 (7FC0E5EB4738) : 8 (DO-ATTACH #<PROMISE name: "promisify: (REMOVE-IF (LAMBDA (NOTE) (LET ((BOARD-ID (GETHASH \"board_id\" NOTE))) (AND BOARD-ID (NOT (FIND BOARD-ID BOARD-IDS :TEST 'STRING=))))) NOTES)" finished: T errored: NIL forward: NIL #x3020028FF13D> #<COMPILED-LEXICAL-CLOSURE #x3020028FEF0F> :NAME "attach: (REMOVE-IF (LAMBDA (NOTE) (LET ((BOARD-ID (GETHASH \"board_id\" NOTE))) (AND BOARD-ID (NOT (FIND BOARD-ID BOARD-IDS :TEST 'STRING=))))) NOTES)") 541
 (7FC0E5EB4780) : 9 (FUNCALL #'#<(:INTERNAL BLACKBIRD-BASE:DO-ATTACH)> #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD>)) 1077
 (7FC0E5EB4818) : 10 (RUN-PROMISE #<PROMISE finished: T errored: NIL forward: NIL #x3020028AB7CD>) 661
 (7FC0E5EB4858) : 11 (FINISH #<PROMISE finished: T errored: NIL forward: NIL #x3020028AB7CD> #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD>)) 453
 (7FC0E5EB4890) : 12 (FUNCALL #'#<(:INTERNAL BLACKBIRD-BASE:DO-ATTACH)> #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD>)) 1077
 (7FC0E5EB4928) : 13 (RUN-PROMISE #<PROMISE name: "attach: #:|finished-promise211162|" finished: T errored: NIL forward: NIL #x3020028ABA5D>) 661
 (7FC0E5EB4968) : 14 (FINISH #<PROMISE name: "attach: #:|finished-promise211162|" finished: T errored: NIL forward: NIL #x3020028ABA5D> #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD>)) 453
 (7FC0E5EB49A0) : 15 (FUNCALL #'#<(:INTERNAL BLACKBIRD-BASE:DO-ATTACH)> #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028D08AD>) #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD>) #<HASH-TABLE :TEST EQUAL size 1/60 #x3020028ACCBD> NIL) 1309
 (7FC0E5EB4A38) : 16 (RUN-PROMISE #<PROMISE finished: T errored: NIL forward: NIL #x3020028B29FD>) 661
 (7FC0E5EB4A78) : 17 (FINISH #<PROMISE finished: T errored: NIL forward: NIL #x3020028B29FD> #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028D08AD>) #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD>) #<HASH-TABLE :TEST EQUAL size 1/60 #x3020028ACCBD> NIL) 453
 (7FC0E5EB4AB0) : 18 (FUNCALL #'#<(:INTERNAL BLACKBIRD-BASE:DO-ATTACH)> #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD>)) 1077
 (7FC0E5EB4B48) : 19 (RUN-PROMISE #<PROMISE finished: T errored: NIL forward: NIL #x3020028ADF8D>) 661
 (7FC0E5EB4B88) : 20 (FINISH #<PROMISE finished: T errored: NIL forward: NIL #x3020028ADF8D> #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD>)) 453
 (7FC0E5EB4BC0) : 21 (FUNCALL #'#<(:INTERNAL BLACKBIRD-BASE:DO-ATTACH)> #(#<HASH-TABLE :TEST EQUAL size 6/60 #x3020028C64AD>)) 1077
 (7FC0E5EB4C58) : 22 (RUN-PROMISE #<PROMISE name: "attach: (CL-RETHINKDB:TO-ARRAY SOCK CURSOR)" finished: T errored: NIL forward: NIL #x3020028C1BDD>) 661
 (7FC0E5EB4C98) : 23 (DO-ATTACH-ERRBACK #<PROMISE name: "attach: (CL-RETHINKDB:TO-ARRAY SOCK CURSOR)" finished: T errored: NIL forward: NIL #x3020028C1BDD> (#<PROMISE finished: NIL errored: NIL forward: NIL #x3020028ADDAD> . #<COMPILED-LEXICAL-CLOSURE # #x3020028ADE1F>)) 373
 (7FC0E5EB4CE0) : 24 (SETUP-PROMISE-FORWARD #<PROMISE name: "attach: (CL-RETHINKDB:RUN SOCK QUERY)" finished: NIL errored: NIL forward: NIL #x3020028D777D> #<PROMISE name: "attach: (CL-RETHINKDB:TO-ARRAY SOCK CURSOR)" finished: T errored: NIL forward: NIL #x3020028C1BDD>) 277
 (7FC0E5EB4D10) : 25 (FUNCALL #'#<(:INTERNAL BLACKBIRD-BASE:FINISH)>) 157
 (7FC0E5EB4D38) : 26 (FINISH #<PROMISE name: "attach: (CL-RETHINKDB:RUN SOCK QUERY)" finished: NIL errored: NIL forward: NIL #x3020028D777D> #<PROMISE name: "attach: (CL-RETHINKDB:TO-ARRAY SOCK CURSOR)" finished: T errored: NIL forward: NIL #x3020028C1BDD>) 453
 (7FC0E5EB4D70) : 27 (FUNCALL #'#<(:INTERNAL BLACKBIRD-BASE:DO-ATTACH)> #<CL-RETHINKDB:CURSOR #x3020028DBB0D> NIL) 1309
 (7FC0E5EB4E08) : 28 (RUN-PROMISE #<PROMISE finished: T errored: NIL forward: NIL #x3020028D871D>) 661
 (7FC0E5EB4E48) : 29 (FINISH #<PROMISE finished: T errored: NIL forward: NIL #x3020028D871D> #<CL-RETHINKDB:CURSOR #x3020028DBB0D> NIL) 453
 (7FC0E5EB4E80) : 30 (FUNCALL #'#<(:INTERNAL BLACKBIRD-BASE:DO-TAP)> NIL) 157
 (7FC0E5EB4EB8) : 31 (FUNCALL #'#<(:INTERNAL BLACKBIRD-BASE:DO-ATTACH)> NIL) 1077
 (7FC0E5EB4F50) : 32 (RUN-PROMISE #<PROMISE name: "promisify: (APPLY TAP-FN VALS)" finished: T errored: NIL forward: NIL #x3020028C36CD>) 661
 (7FC0E5EB4F90) : 33 (DO-ATTACH #<PROMISE name: "promisify: (APPLY TAP-FN VALS)" finished: T errored: NIL forward: NIL #x3020028C36CD> #<COMPILED-LEXICAL-CLOSURE (:INTERNAL BLACKBIRD-BASE:DO-TAP) #x3020028C344F> :NAME "attach: (APPLY TAP-FN VALS)") 541
 (7FC0E5EB4FD8) : 34 (FUNCALL #'#<(:INTERNAL BLACKBIRD-BASE:DO-ATTACH)> #<CL-RETHINKDB:CURSOR #x3020028DBB0D> NIL) 1077
 (7FC0E5EB5070) : 35 (RUN-PROMISE #<PROMISE finished: T errored: NIL forward: NIL #x3020028C7F5D>) 661
 (7FC0E5EB50B0) : 36 (DO-ATTACH-ERRBACK #<PROMISE finished: T errored: NIL forward: NIL #x3020028C7F5D> (#<PROMISE finished: NIL errored: NIL forward: NIL #x3020028D854D> . #<COMPILED-LEXICAL-CLOSURE # #x3020028D85BF>)) 373
 (7FC0E5EB50F8) : 37 (SETUP-PROMISE-FORWARD #<PROMISE finished: NIL errored: NIL forward: NIL #x3020028D948D> #<PROMISE finished: T errored: NIL forward: NIL #x3020028C7F5D>) 277
 (7FC0E5EB5128) : 38 (FUNCALL #'#<(:INTERNAL BLACKBIRD-BASE:FINISH)>) 157
 (7FC0E5EB5150) : 39 (FINISH #<PROMISE finished: NIL errored: NIL forward: NIL #x3020028D948D> #<PROMISE finished: T errored: NIL forward: NIL #x3020028C7F5D>) 453
 (7FC0E5EB5188) : 40 (CALL-WITH-CALLBACK-RESTARTS #<COMPILED-LEXICAL-CLOSURE (:INTERNAL #:THUNK-FN53822 CL-ASYNC::STREAMISH-READ-CB) #x3020028C8DFF> :CONTINUE-FN #<COMPILED-LEXICAL-CLOSURE (:INTERNAL #:THUNK-FN53822 CL-ASYNC::STREAMISH-READ-CB) #x3020028C8DAF> :ABORT-RESTART-DESCRIPTION "Abort cl-async callback.") 1213
 (7FC0E5EB5220) : 41 (STREAMISH-READ-CB #<A Foreign Pointer #x7FC0E0093560> 661 #<A Foreign Pointer #x7FC0E61164A0>) 1645
 (7FC0E5EB52F8) : 42 (FUNCALL #'#<CFFI-CALLBACKS::|CL-ASYNC::STREAMISH-READ-CB|> 17558308793482) 373
 (7FC0E5EB5330) : 43 (%PASCAL-FUNCTIONS% 11 17558308793482) 397
 (7FC0E5EB53F0) : 44 (UV-RUN #<A Foreign Pointer [stack-allocated] #x7FC0E6119860> 0) 261
 (7FC0E5EB5418) : 45 (START-EVENT-LOOP #<COMPILED-LEXICAL-CLOSURE (:INTERNAL TURTL:START) #x30200286163F> :CATCH-APP-ERRORS NIL :SEND-ERRORS-TO-EVENTCB T) 2637
 (7FC0E5EB5560) : 46 (START :BIND NIL :PORT 8181) 1149
 (7FC0E5EB5620) : 47 (CALL-CHECK-REGS TURTL:START :PORT 8181) 221
 (7FC0E5EB5658) : 48 (FUNCALL #'#<(:INTERNAL CCL::WITH-COMPILATION-UNIT-BODY CCL::LOAD-FROM-STREAM)>) 765
 (7FC0E5EB56E8) : 49 (CALL-WITH-COMPILATION-UNIT #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::WITH-COMPILATION-UNIT-BODY CCL::LOAD-FROM-STREAM) #x7FC107004BCF> :OVERRIDE NIL) 197
 (7FC0E5EB5730) : 50 (LOAD-FROM-STREAM #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/opt/api/start.lisp"/5 UTF-8) #x3020008957AD> NIL) 389
 (7FC0E5EB5770) : 51 (%LOAD #P"/opt/api/start.lisp" NIL NIL :ERROR :DEFAULT NIL) 5341
 (7FC0E5EB58D0) : 52 (LOAD "start" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT :PRESERVE-OPTIMIZATION-SETTINGS NIL) 1061
 (7FC0E5EB5988) : 53 (CALL-CHECK-REGS LOAD "start") 221
 (7FC0E5EB59C0) : 54 (FUNCALL #'#<(:INTERNAL CCL::WITH-COMPILATION-UNIT-BODY CCL::LOAD-FROM-STREAM)>) 765
 (7FC0E5EB5A50) : 55 (CALL-WITH-COMPILATION-UNIT #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::WITH-COMPILATION-UNIT-BODY CCL::LOAD-FROM-STREAM) #x7FC107004FEF> :OVERRIDE NIL) 197
 (7FC0E5EB5A98) : 56 (LOAD-FROM-STREAM #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/opt/api/launch.lisp"/4 UTF-8) #x302000896D2D> NIL) 389
 (7FC0E5EB5AD8) : 57 (%LOAD #P"/opt/api/launch.lisp" NIL NIL :ERROR :DEFAULT NIL) 5341
 (7FC0E5EB5C38) : 58 (LOAD "launch.lisp" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT :PRESERVE-OPTIMIZATION-SETTINGS NIL) 1061
 (7FC0E5EB5CF0) : 59 (FUNCALL #'#<(:INTERNAL CCL::LOAD-FILE CCL::STARTUP-CCL)> "launch.lisp") 493
 (7FC0E5EB5D38) : 60 (STARTUP-CCL ("home:ccl-init" "home:\\.ccl-init")) 1693
 (7FC0E5EB5DA8) : 61 (FUNCALL #'#<(:INTERNAL (TOPLEVEL-FUNCTION (CCL::LISP-DEVELOPMENT-SYSTEM T)))>) 61
 (7FC0E5EB5DC8) : 62 (FUNCALL #'#<(:INTERNAL CCL::MAKE-MCL-LISTENER-PROCESS)>) 661
 (7FC0E5EB5E60) : 63 (RUN-PROCESS-INITIAL-FORM #<TTY-LISTENER listener(1) [Active] #x302000425CCD> (#<COMPILED-LEXICAL-CLOSURE # #x3020004257FF>)) 709
 (7FC0E5EB5EF0) : 64 (FUNCALL #'#<(:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS)))> #<TTY-LISTENER listener(1) [Active] #x302000425CCD> (#<COMPILED-LEXICAL-CLOSURE # #x3020004257FF>)) 573
 (7FC0E5EB5F98) : 65 (FUNCALL #'#<(:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION)>) 277

**Comment by szimszon** [comment]
I use ftp://ftp.clozure.com/pub/release/1.11/ccl-1.11-linuxx86.tar.gz ...

**Comment by szimszon** [comment]
One more thing. The turtl server is behind apache2 proxy. (Desktop client still works.)

**Comment by dauphin327** [comment]
Getting this error too on android client when trying to connect, running ccl arm.

**Comment by ArthurGarnier** [comment]
Same error : 

`juin 08 13:36:55 arthurgarnier.fr docker[2618]: <INFO> [11:36:55] wookie - "POST /auth" 200 26
juin 08 13:36:55 arthurgarnier.fr docker[2618]: <INFO> [11:36:55] wookie - "GET /users/57252d6871a38b0081000001" 20
juin 08 13:36:55 arthurgarnier.fr docker[2618]: > Error: NIL found instead of hash table
juin 08 13:36:55 arthurgarnier.fr docker[2618]: > While executing: CL-HASH-UTIL:HGET, in process listener(1).
juin 08 13:36:55 arthurgarnier.fr docker[2618]: > Type :GO to continue, :POP to abort, :R for a list of available r
juin 08 13:36:55 arthurgarnier.fr docker[2618]: > If continued: Skip loading "launch.lisp"
juin 08 13:36:55 arthurgarnier.fr docker[2618]: > Type :? for other options.
`

But from the desktop it works (if I restart the server...)

`juin 08 13:38:02 arthurgarnier.fr docker[3200]: <INFO> [11:38:02] wookie - "POST /auth" 200 26
juin 08 13:38:03 arthurgarnier.fr docker[3200]: <INFO> [11:38:03] wookie - "GET /users/57252d6871a38b0081000001" 20
juin 08 13:38:03 arthurgarnier.fr docker[3200]: <INFO> [11:38:03] wookie - "GET /sync" 200 4
`

**Comment by orthecreedence** [comment]
This was a bug introduced into a supporting library (cl-hash-util).

What you want to do is go into your `quicklisp/local-projects/` folder and do `git clone git://github.com/orthecreedence/cl-hash-util`

That should fix it

**Comment by szimszon** [comment]
It seem it works now...
