### ISSUE TITLE
Self-hosted errors

### ISSUE THREAD

**Issue by farfeduc** [turtl/api#6]
Hi ! I hope someone can help me.

I'm using a Docker container to run the turtl API.
You can find my image here : [My Docker Container](https://github.com/farfeduc/docker-turtl)

I had first an issue with this line : `(setf vom:*time-formatter* (lambda () (turtl::get-timestamp)))` in start.lisp

So I forked the API and removed this line. 

Now the API starts fine.

The issue is now with the client or my reverse proxy.

When I go over https and try to create a new account I get the following error : 

`Couldn't connect to server` in the client (I have the same SSL protocols as the official API, and a valid SSL certificate).

And when I go over http, I have the following error in the client : 

`There was a problem saving that account undefined`

And this is the log on the server : (and the api server restarts)

Is there an issue with the schema ?

```bash
While evaluating the form starting at line 5, column 0
  of #P"/turtl/start.lisp":

debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1002AAC0F3}>:
  The value
    "AAUCAAE0MDAxNTY3MmFkNDY1MDA07Q7058Ul9BidAR4VL87MPrvsq2CiS/y1NYpJjV1vECqDkeyMckRt2tBRu8gm1Kcm8OC5mXF00hvPJPRo2uZ4AnAEe57rgc58FffpJdoTqmAlxbqm2u9NHDN9xq3wSRQJmfFP957bbSuo+JHyrPZC/sr9jBWwmKzQBTRGUXB3qCQFapiE7wcMQqA6zSaYfhZH6+Y="
  is not of type
    SIMPLE-STRING.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [REJECT-PROMISE     ] Reject the promise #<PROMISE finished: NIL errored: NIL forward: NIL {10036210C3}>
  1:                       Reject the promise #<PROMISE name: "promisify: (CL-RETHINKDB:RUN SOCK QUERY)" finished: NIL errored: NIL forward: NIL {1003620F23}>
  2:                       Reject the promise #<PROMISE name: "promisify: (CL-RETHINKDB-REQL:R
             (:LIMIT
              (:GET-ALL (:TABLE \"users\") AUTH-KEY :INDEX
               (DB-INDEX \"users\" \"a\"))
              1))" finished: T errored: NIL forward: NIL {10035154F3}>
  3:                       Reject the promise #<PROMISE name: "attach: (DO-CONNECT HOST PORT :READ-TIMEOUT READ-TIMEOUT)" finished: NIL errored: NIL forward: T {1003509D03}>
  4: [CONTINUE-EVENT-LOOP] Continue the event loop, passing the error to the default handler.
  5: [ABORT-CALLBACK     ] Abort cl-async callback.
  6: [EXIT-EVENT-LOOP    ] Exit the current event loop.
  7: [RETRY              ] Retry EVAL of current toplevel form.
  8: [CONTINUE           ] Ignore error and continue loading file "/turtl/start.lisp".
  9: [ABORT              ] Abort loading file "/turtl/start.lisp".
 10:                       Exit debugger, returning to top level.

((:METHOD JONATHAN.ENCODE:%TO-JSON (STRING)) #<unavailable argument>) [fast-method]
0] ```

**Comment by orthecreedence** [comment]
Hello, sorry for the late response. It looks like you're using SBCL. Try [clozure cl](http://ccl.clozure.com/download.html) instead. I'm still working on some fixes for SBCL.

**Comment by farfeduc** [comment]
Thank you !

It Works :)

I will publish my Dockerfile on my github account soon.

Le sam. 25 juin 2016 à 18:28, andrew lyon <notifications@github.com> a
écrit :

**Comment by psjbeisler** [comment]
Clozure CL is not supported with my distro and i still get this error with sbcl, so technically i cant do anything atm.

**Comment by farfeduc** [comment]
What distro is it ?

Because you juste have to clone the svn repository of Clozure CL to make it
run on any linux, darwin, windows and even ARM distribution.

Le ven. 12 août 2016 à 13:42, Patrick Beisler <notifications@github.com> a
écrit :

**Comment by psjbeisler** [comment]
it was my fault missing dependencies for the build, like m4.
SBCL is officially supported by Arch and some others while I cant find any support for Clozure.
Also it was recommended in the documentation to use SBCL for Linux while it is also known to not work atm. (as mentioned above)
