### ISSUE TITLE
Uploaded image

### ISSUE THREAD

**Issue by szimszon** [turtl/api#7]
Hi,

I have a problem, if there is a picture uploaded and I try to sync with android I get:

turtl_1  | <NOTICE> [17:49:35] turtl - *a :: {"event":"log","data":{"data":{"line":332,"url":"file:///android_asset/www/app/controllers/notes/view.js","msg":"Uncaught TypeError: Cannot read property 'replace' of undefined","version":"0.6.4","client":"mobile-android"},"hash":"7118183d056b4b59f75f61d3985e41e8"}}

With desktop client the result is the same:
turtl_1  | <NOTICE> [17:55:22] turtl - *a :: {"event":"log","data":{"data":{"line":332,"url":"/data/app/controllers/notes/view.js","msg":"Uncaught TypeError: Cannot read property 'replace' of undefined","version":"0.6.4","client":"desktop"},"hash":"81158cbb6cdf3dd9d79cb288463c80e6"}}

**Comment by ldidry** [comment]
I gome the same problem: the text notes are syncing well but files are not.

**Comment by orthecreedence** [comment]
Thanks, I *think* https://github.com/turtl/js/commit/16dc45ca20bead25c4421c3d852d7991b5da6de5 fixes this but need to confim.

**Comment by ldidry** [comment]
Thx, this works to me. :+1:

**Comment by szimszon** [comment]
I have still issues after I unzipped the package.nw editted a files from the commit turtl/js@16dc45c zipped it and replaced the original package.nw :(

**Comment by orthecreedence** [comment]
@szimszon same problem? or are you getting a different error in the console?

**Comment by szimszon** [comment]
Now I didn't see the error messages in logs but I still get 

"There was a problem opening that file: undefined"

in the user interface if I click in the attachment and no image is displayed.

**Comment by szimszon** [comment]
Okay. Sorry I had the same issue as in #16 I had to define the upload url in config :)

We can close - I think - both issues :)
